inherit_from:
  - lib/modified_cops.yml
  - lib/disabled_cops.yml

AllCops:
  DisplayCopNames: true
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - '**/*.rake'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
